export const propertyFilters = {
  price_range: {
    min: "No Min",
    max: "No Max",
    type: "range",
  },
  beds: {
    type: "selection",
    options: ["ANY", "1", "2", "3", "4+"],
  },
  baths: {
    type: "selection",
    options: ["ANY", "1", "2", "3", "4+"],
  },
  property_type: {
    type: "multi-select",
    options: [
      "Business Opportunity",
      "Commercial Sale",
      "Condo/Townhome",
      "Farm/Ranch",
      "Manufactured Home",
      "Multi-Family",
      "Residential",
      "Residential Lease",
      "Vacant Land",
    ],
  },
  property_status: {
    type: "multi-select",
    options: [
      "All",
      "Active",
      "Pending",
      "Active with contingency",
      "Open Houses",
      "New Listings",
      "Price Reduced",
    ],
  },
  sqft: {
    min: "No Min",
    max: "No Max",
    type: "range",
  },
  lot_size: {
    min: "No Min",
    max: "No Max",
    type: "range",
  },
  year_built: {
    min: "No Min",
    max: "No Max",
    type: "range",
  },
  garage: {
    min: "No Min",
    max: "No Max",
    type: "range",
  },
  popular_features: {
    type: "multi-select",
    options: ["Basement", "Waterfront", "New Construction"],
  },
  community_features: {
    type: "multi-select",
    options: [
      "Golf Community",
      "Boat Launch",
      "Tennis Courts",
      "Community Waterfront/Pvt",
      "Airfield",
      "Gated",
      "Golf",
      "Senior Community",
      "No CCRs",
      "Has CCRs",
      "No Age Restrictions",
    ],
  },
  interior_features: {
    type: "multi-select",
    options: [
      "Basement: Daylight",
      "Built-In Vacuum",
      "Loft",
      "Security System",
      "Wired for Generator",
      "2nd Master Bedroom",
      "Hardwood",
      "Basement: Finished",
      "Second Kitchen",
      "Basement: Partially Finished",
      "Basement: Unfinished",
      "Master on Main",
      "Furnished",
      "Second Primary Bedroom",
      "Elevator",
    ],
  },
  parking_features: {
    type: "multi-select",
    options: ["Off Street", "RV Parking", "Attached Garage", "Common Garage"],
  },
  view: {
    type: "multi-select",
    options: [
      "Bay",
      "City",
      "Golf Course",
      "Jetty",
      "Lake",
      "Ocean",
      "River",
      "Sound",
      "Strait",
      "Canal",
      "Mountain(s)",
    ],
  },
  heating: {
    type: "multi-select",
    options: [
      "90%+ High Efficiency",
      "Baseboard",
      "Ductless HP-Mini Split",
      "Electric",
      "Forced Air",
      "Heat Pump",
      "HEPA Air Filtration",
      "High Efficiency (Unspecified)",
      "HRV/ERV System",
      "Insert",
      "Natural Gas",
      "Oil",
      "Pellet",
      "Propane",
      "Radiant",
      "Solar (Unspecified)",
      "Solar PV",
      "Tankless Water Heater",
      "Wood",
      "Hot Water Recirculation Pump",
    ],
  },
  financial_information: {
    type: "multi-select",
    options: [
      "Cash Out",
      "Farm Home Loan",
      "FHA",
      "Owner Financing",
      "Rehab Loan",
      "State Bond",
      "VA Loan",
      "USDA Loan",
      "Has HOA",
      "No HOA",
      "Conventional",
      "Assumable",
      "Short Sale",
      "Bank Or REO",
    ],
  },
  home_style: {
    type: "multi-select",
    options: [
      "Townhouse",
      "Contemporary",
      "Craftsman",
      "NW Contemporary",
      "Duplex",
      "Triplex",
      "Quadruplex",
      "Dock",
      "Floating House",
      "Cabin",
    ],
  },
  heating_features: {
    type: "multi-select",
    options: ["Stove/Free Standing", "Central A/C"],
  },
  property_subtypes: {
    type: "multi-select",
    options: ["ADU", "Condominium"],
  },
  lot_features: {
    type: "multi-select",
    options: [
      "Bank-Medium",
      "No Bank",
      "Bank-High",
      "Bulkhead",
      "Lake",
      "Creek",
      "Saltwater",
      "Sound",
      "Strait",
      "Tideland Rights",
      "Fenced-Fully",
      "RV Parking",
      "Sprinkler System",
      "Shop",
      "Bay/Harbor",
      "Green House",
      "Electric Car Charging",
      "Zoning: HDC-1",
      "River Access",
    ],
  },
  pool_features: {
    type: "multi-select",
    options: ["Community", "Above Ground", "In-Ground", "Indoor"],
  },
  green_features: {
    type: "multi-select",
    options: ["High Efficiency - 90%+", "Insulated Windows"],
  },
  stories: {
    type: "multi-select",
    options: ["1 Story", "2 Story", "3+ Story"],
  },
  exterior_features: {
    type: "multi-select",
    options: [
      "Under Construction",
      "Average",
      "Very Good",
      "Good",
      "Fair",
      "Fixer",
      "Has ADU",
      "Remodeled",
    ],
  },
  property_features: {
    type: "multi-select",
    options: ["Equestrian", "Pasture Land"],
  },
};
